{% set name = "rfpimp" %}
{% set version = "1.2" %}
{% set sha256 = "4456c7b67ddaf2d732db0a2663e71370fdd95c8ab9b012a18abe0dae9d102a47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - matplotlib

test:
  imports:
    - rfpimp

about:
  home: https://github.com/parrt/random-forest-importances
  license: MIT
  license_family: MIT
  summary: 'Code to compute permutation and drop-column importances in Python scikit-learn random forests'

extra:
  recipe-maintainers:
    - ericmjl
