travis:
  secure:
    BINSTAR_TOKEN: VtJ+E8z1rarvTIJWB0wt/9oOOXECmi6vfOM4AIl5YO3bA4jf2nKe+1BiVeU/+koKgjyFl9Lwgvh+5/ZC4XkdGpFpgSTbCaZEXiVB/DUSZ8Q3/enuwM1+J+ZaEhklGM1XDhe3Z7OJBkSxRNGF7wqFYru45tIQ6EMnILOK68b5DcqkYfecdmndUeE0gdImMoM+TWs3NdGdRqITlrY6OLcewV9p8Q7k1Q10qwW4hhdsTW99k++IfIC51DadTYxGjnsBhqyKbRDK4FlBWDTtLCyXjFom4HyGBUI7RcijOBQyAG87E+cZ3r7voI4DmEKbXihBUvKVmQxSmhLtMsmHB11Co6yBH2NpC7+6bWzL8luXl9LEg+Gi5YFV1uiagBQafeWTGmh5mRhP4NbUBhQBtfs+gaku36q6jpFleSncjrKbCKGdyBSvDfrK/AjaFGBXCIM855NLvx9LMKGGYS2gVFZxM6fPU4A9AjDsOqL4iMqyFnZRUO4K74GHOjxS2QcuJyO16AGghOkpmFVRaTHEOM1cyCterNs+Oq+otARqyE54w0dltt/MQIxrVnvKwwSIBjMxm3qgNy6ayKvzOjoqmqHF3ywBpBYagBuTRyrsKf8jE4W6rK9fiK/fHHQBs3jr2M4U4iQy7Zy6xcDjl7CPeyt5v8HRqGYP2KmZaft7SxsJj3I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
