travis:
  secure:
    BINSTAR_TOKEN: P/8BQIzIJ8fQGLDlNMmHvWtfNywJS3vS41CfGt2eVM2BZsXo028XeYFF4JFwwKnCr4Oza57ixLWYT143oLO1cSJ3YJ0UcNhPkEY3xMPfA3axovLbZKsxmyd0GnHw/zziOb5u9xm3i60Ns3CqMreDJAy4jsMfE5fRmIYYRbTw3+hYot1q4wGJYmKp6TajlW0k3Kq1GoZmpjYU6Vk0YeN7wwS6v7PPTA2GYBvS0gc9sNE2XG5l/ziRAsfWx8DGrVmUudxtTIAU3ViCgpAvcCdLe0L/WpciFY+La90uqAvNT9WyD655tXabow6YmWMBVPYgobDG9/2Czj4yqwpNNDPdeZZMrByOVvjeQ6VmSPz6s82Vvo7zqP00HpsVVjROgtR7ZKPgZfomTHQKMcKf5YXTi5jHcOKQYl4qNiKe0vYhBvIDQzdtFptpyhGhnZkvVPAGlVNyjwamWDsxO6nUJCqAxN7N7Ips4JlF32GbAb8eUafQ1r8mYR9KPSQaIW4BliTnO0P0TNzSKPGO05H74MtX2IyPmp9Cmc5jkNXqGsLAegIi3qMgpeWJchrGlQ15vWX9nnmDYfzS4dnHTv6qivbJs3u02NUvS6yqIciuH7wMWMaP6QRVP1Ya76K076UeCNBMKHmqpYk0SK/Q+u9y0pu6ivCsZF2whbwR9/kyg7YP+mg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
